### ISSUE TITLE
Vue warning when rendering `VwcTextField` without explicit `size` prop

### ISSUE THREAD

**Issue by GREsau** [Vonage/vivid-bindings-vue#12]
Probably caused by #8 (whoops!)

When running in debug mode and rendering a `<VwcTextField>` without a `size` prop, a warning similar to the following is logged:
```
[Vue warn]: Failed setting prop "size" on <vvd3-text-field>: value undefined is invalid.
  DOMException: Failed to set the 'size' property on 'HTMLInputElement': The value provided is 0, which is an invalid size.
    at Decorated.sizeChanged (http://localhost:4200/...)
---snip---
    at ReactiveEffect.run (http://localhost:4200/...) 
  at <VwcTextField icon="search-line" placeholder="Search..." value=""  ... > 
```

I think this is because `size` is declared as an optional prop of `VwcTextField`, so omitting it is equivalent to passing `:size="undefined"` - but the underlying web component does not accept `undefined` as a value for `size`.

I don't think vivid-vue has this problem, because it passes its props to the underlying web component with code of the form:
```
...(this.size !== undefined ? {'size': this.size } : {})
```
i.e. if the Vue component's `size` prop is `undefined` (or omitted), then it won't forward it into underlying the web component at all

I don't believe this causes any user impact, it's just some unfortunate log spam in the browser console - so we may opt to just ignore it until we eventually migrate to vivid-vue.

**Comment by k-paxian** [comment]
Fixed by https://github.com/Vonage/vivid-bindings-vue/commit/bb3d055064287e1cf7b4b38d119966eee331020c and https://github.com/Vonage/vivid-bindings-vue/commit/3c0c89b2aad9255dc462b2c0d09a3e784e4002f1
